create table Users(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(50) NOT NULL UNIQUE,
    email varchar(50) NOT NULL UNIQUE,
    phone_number varchar(50) UNIQUE,
    password varchar (50)
)